[env]
PROJECT_SLUG = '{{ config_root | basename | slugify }}'

_.python.venv.path = '{% if env.UV_PROJECT_ENVIRONMENT %}{{ env.UV_PROJECT_ENVIRONMENT }}{% else %}.venv{% endif %}'
_.python.venv.create = true


[task_config]
includes = [
    'tasks',
]


[settings]
# Coppy projects uses .python-version because both mise and uv respect it.
idiomatic_version_file_enable_tools = ['python']
